// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Demo(Props) {
  return React.createElement("div", undefined, "Hsasdello Wosrld");
}

var make = Demo;

export {
  make ,
  
}
/* react Not a pure module */
